import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, BookOpenCheck, CircleCheck, GraduationCap, LibraryBig, MessageSquareText } from "lucide-react";
import { AcademyShell } from "@/components/academy-shell";
import { CourseCard, Eyebrow } from "@/components/academy-ui";
import { Button } from "@/components/ui/button";
import { courses } from "@/data/academy";
import hero from "@/assets/academy-hero.jpg";
import students from "@/assets/students-seminar.jpg";
import instructor from "@/assets/instructor-amaka.jpg";
export const Route=createFileRoute("/")({head:()=>({meta:[{title:"Ozikoro Academy — Igbo language, history and culture"},{name:"description",content:"Structured courses in Igbo language, African history, culture and research."},{property:"og:title",content:"Ozikoro Academy"},{property:"og:description",content:"Serious learning in Igbo language, history and cultural scholarship."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:Home});
function Home(){return <AcademyShell><section className="academy-hero"><img src={hero} alt="An elder scholar studying an archival manuscript" width={1600} height={1056}/><div className="hero-shade"/><div className="site-wrap hero-copy"><Eyebrow light>Knowledge carried forward</Eyebrow><h1>Study language, history<br/>and <em>the ideas that endure.</em></h1><p>Rigorous courses in Igbo language and African cultural scholarship, guided by trusted instructors and carefully sourced materials.</p><div className="flex flex-wrap gap-3"><Button asChild size="lg" variant="gold"><Link to="/courses">Explore courses <ArrowRight/></Link></Button><Button asChild size="lg" variant="heroOutline"><Link to="/programmes">View programmes</Link></Button></div></div><div className="hero-credit">Ozikoro Academy · Archival learning</div></section>
<section className="border-b border-border bg-surface"><div className="site-wrap grid md:grid-cols-3"><Stat n="24" label="Structured courses"/><Stat n="8" label="Learning pathways"/><Stat n="12" label="Academic instructors"/></div></section>
<section className="section-pad"><div className="site-wrap"><div className="section-head"><div><Eyebrow>Begin your study</Eyebrow><h2>Featured courses</h2></div><Link className="text-link" to="/courses">Browse the full catalogue <ArrowRight/></Link></div><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{courses.slice(0,3).map(c=><CourseCard key={c.slug} course={c}/>)}</div></div></section>
<section className="bg-night py-20 text-on-night"><div className="site-wrap grid gap-12 lg:grid-cols-[1.05fr_.95fr]"><div className="self-center"><Eyebrow light>Programmes of study</Eyebrow><h2 className="mt-3 max-w-xl text-on-night">Follow a clear path from first principles to confident practice.</h2><p className="mt-5 max-w-xl font-serif text-lg leading-relaxed text-on-night-muted">Programmes bring connected courses together into focused pathways, with assessments and an Ozikoro certificate at completion.</p><Button asChild variant="gold" className="mt-7"><Link to="/programmes">Explore programmes <ArrowRight/></Link></Button></div><div className="programme-list"><Programme n="01" title="Igbo Language & Expression" meta="4 courses · 24 weeks"/><Programme n="02" title="History, Archive & Community" meta="3 courses · 20 weeks"/><Programme n="03" title="Cultural Research Practice" meta="3 courses · 22 weeks"/></div></div></section>
<section className="section-pad"><div className="site-wrap grid gap-10 lg:grid-cols-2"><img src={students} alt="Students examining archival materials together" loading="lazy" width={1408} height={912} className="aspect-[4/3] h-full w-full object-cover"/><div className="self-center lg:px-8"><Eyebrow>How learning works</Eyebrow><h2 className="mt-3">A serious rhythm for lasting understanding.</h2><div className="mt-8 grid gap-6"><Step icon={<LibraryBig/>} n="01" title="Read and listen" text="Study carefully edited lessons, primary sources, audio and expert commentary."/><Step icon={<BookOpenCheck/>} n="02" title="Practise with purpose" text="Build comprehension, writing, listening and research skills through guided work."/><Step icon={<CircleCheck/>} n="03" title="Demonstrate understanding" text="Complete assessments and receive a record of your academic achievement."/></div></div></div></section>
<section className="border-y border-border bg-surface-sunk py-20"><div className="site-wrap grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><img src={instructor} alt="Ozikoro history instructor" loading="lazy" width={912} height={1104} className="aspect-[4/5] w-full object-cover"/><div className="self-center lg:px-8"><Eyebrow>Learn with scholars</Eyebrow><blockquote className="mt-5 font-serif text-2xl leading-relaxed text-foreground">“We teach learners to ask not only what happened, but how we know—and whose knowledge has been carried forward.”</blockquote><p className="mt-6 font-semibold">Dr Amaka Nwosu</p><p className="text-sm text-muted-foreground">Historian · Oral traditions and community archives</p><Button asChild variant="outline" className="mt-7"><Link to="/instructors">Meet the instructors <ArrowRight/></Link></Button></div></div></section>
<section className="section-pad"><div className="site-wrap grid gap-6 lg:grid-cols-2"><div className="feature-panel"><MessageSquareText/><Eyebrow>Onye Ozi</Eyebrow><h2>Your academic messenger.</h2><p>Ask for a concept to be explained, practise vocabulary, review your writing or generate questions from approved course material.</p><Button asChild><Link to="/onye-ozi">Open Onye Ozi <ArrowRight/></Link></Button></div><div className="feature-panel alt"><GraduationCap/><Eyebrow>Ready to begin?</Eyebrow><h2>Find your first course.</h2><p>Browse by subject, level and duration. Each course sets out its outcomes, syllabus and assessment before you enrol.</p><Button asChild variant="ink"><Link to="/courses">Browse courses <ArrowRight/></Link></Button></div></div></section></AcademyShell>}
function Stat({n,label}:{n:string;label:string}){return <div className="border-border py-6 text-center md:border-r md:last:border-r-0"><b className="font-serif text-3xl text-primary">{n}</b><span className="ml-3 text-sm text-muted-foreground">{label}</span></div>}
function Programme({n,title,meta}:{n:string;title:string;meta:string}){return <Link to="/programmes" className="programme-row"><span>{n}</span><strong>{title}<small>{meta}</small></strong><ArrowRight/></Link>}
function Step({icon,n,title,text}:{icon:React.ReactNode;n:string;title:string;text:string}){return <div className="grid grid-cols-[2.5rem_1fr] gap-4"><div className="step-icon">{icon}</div><div><span className="text-xs font-bold text-primary">{n}</span><h3 className="mt-1 text-lg">{title}</h3><p className="mt-1 text-sm leading-relaxed text-muted-foreground">{text}</p></div></div>}
