/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InstructorsRouteImport } from './routes/instructors'
import { Route as MyLearningRouteImport } from './routes/my-learning'
import { Route as ProgrammesRouteImport } from './routes/programmes'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as AssessmentSlugRouteImport } from './routes/assessment.$slug'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as LearnSlugRouteImport } from './routes/learn.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorsRoute = InstructorsRouteImport.update({
  id: '/instructors',
  path: '/instructors',
  getParentRoute: () => rootRouteImport,
} as any)
const MyLearningRoute = MyLearningRouteImport.update({
  id: '/my-learning',
  path: '/my-learning',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesRoute = ProgrammesRouteImport.update({
  id: '/programmes',
  path: '/programmes',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentSlugRoute = AssessmentSlugRouteImport.update({
  id: '/assessment/$slug',
  path: '/assessment/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnSlugRoute = LearnSlugRouteImport.update({
  id: '/learn/$slug',
  path: '/learn/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/instructors': typeof InstructorsRoute
  '/my-learning': typeof MyLearningRoute
  '/programmes': typeof ProgrammesRoute
  '/resources': typeof ResourcesRoute
  '/assessment/$slug': typeof AssessmentSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/courses/': typeof CoursesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/instructors': typeof InstructorsRoute
  '/my-learning': typeof MyLearningRoute
  '/programmes': typeof ProgrammesRoute
  '/resources': typeof ResourcesRoute
  '/assessment/$slug': typeof AssessmentSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/courses': typeof CoursesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/instructors': typeof InstructorsRoute
  '/my-learning': typeof MyLearningRoute
  '/programmes': typeof ProgrammesRoute
  '/resources': typeof ResourcesRoute
  '/assessment/$slug': typeof AssessmentSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/courses/': typeof CoursesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/instructors'
    | '/my-learning'
    | '/programmes'
    | '/resources'
    | '/assessment/$slug'
    | '/courses/$slug'
    | '/learn/$slug'
    | '/courses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/instructors'
    | '/my-learning'
    | '/programmes'
    | '/resources'
    | '/assessment/$slug'
    | '/courses/$slug'
    | '/learn/$slug'
    | '/courses'
  id:
    | '__root__'
    | '/'
    | '/instructors'
    | '/my-learning'
    | '/programmes'
    | '/resources'
    | '/assessment/$slug'
    | '/courses/$slug'
    | '/learn/$slug'
    | '/courses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InstructorsRoute: typeof InstructorsRoute
  MyLearningRoute: typeof MyLearningRoute
  ProgrammesRoute: typeof ProgrammesRoute
  ResourcesRoute: typeof ResourcesRoute
  AssessmentSlugRoute: typeof AssessmentSlugRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
  LearnSlugRoute: typeof LearnSlugRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructors': {
      id: '/instructors'
      path: '/instructors'
      fullPath: '/instructors'
      preLoaderRoute: typeof InstructorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-learning': {
      id: '/my-learning'
      path: '/my-learning'
      fullPath: '/my-learning'
      preLoaderRoute: typeof MyLearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes': {
      id: '/programmes'
      path: '/programmes'
      fullPath: '/programmes'
      preLoaderRoute: typeof ProgrammesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/$slug': {
      id: '/assessment/$slug'
      path: '/assessment/$slug'
      fullPath: '/assessment/$slug'
      preLoaderRoute: typeof AssessmentSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$slug': {
      id: '/learn/$slug'
      path: '/learn/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof LearnSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InstructorsRoute: InstructorsRoute,
  MyLearningRoute: MyLearningRoute,
  ProgrammesRoute: ProgrammesRoute,
  ResourcesRoute: ResourcesRoute,
  AssessmentSlugRoute: AssessmentSlugRoute,
  CoursesSlugRoute: CoursesSlugRoute,
  LearnSlugRoute: LearnSlugRoute,
  CoursesIndexRoute: CoursesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
