/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as CertificatesRouteImport } from './routes/certificates'
import { Route as ClassroomRouteImport } from './routes/classroom'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as InstructorsRouteImport } from './routes/instructors'
import { Route as MapRouteImport } from './routes/map'
import { Route as MasteryRouteImport } from './routes/mastery'
import { Route as MyLearningRouteImport } from './routes/my-learning'
import { Route as OnyeOziRouteImport } from './routes/onye-ozi'
import { Route as ProgrammesRouteImport } from './routes/programmes'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SearchRouteImport } from './routes/search'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as TranscriptRouteImport } from './routes/transcript'
import { Route as AssessmentSlugRouteImport } from './routes/assessment.$slug'
import { Route as ChallengeSlugRouteImport } from './routes/challenge.$slug'
import { Route as CollectionsSlugRouteImport } from './routes/collections.$slug'
import { Route as ConceptsSlugRouteImport } from './routes/concepts.$slug'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as CulturesSlugRouteImport } from './routes/cultures.$slug'
import { Route as DiagnosticSlugRouteImport } from './routes/diagnostic.$slug'
import { Route as LearnSlugRouteImport } from './routes/learn.$slug'
import { Route as PathsIndexRouteImport } from './routes/paths.index'
import { Route as PathsSlugRouteImport } from './routes/paths.$slug'
import { Route as PracticeSlugRouteImport } from './routes/practice.$slug'
import { Route as ProgrammesSlugRouteImport } from './routes/programmes.$slug'
import { Route as RegionsSlugRouteImport } from './routes/regions.$slug'
import { Route as ResearchSlugRouteImport } from './routes/research.$slug'
import { Route as SourcesSlugRouteImport } from './routes/sources.$slug'
import { Route as SubjectsSlugRouteImport } from './routes/subjects.$slug'
import { Route as UnitsSlugRouteImport } from './routes/units.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesRoute = CertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassroomRoute = ClassroomRouteImport.update({
  id: '/classroom',
  path: '/classroom',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorsRoute = InstructorsRouteImport.update({
  id: '/instructors',
  path: '/instructors',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const MasteryRoute = MasteryRouteImport.update({
  id: '/mastery',
  path: '/mastery',
  getParentRoute: () => rootRouteImport,
} as any)
const MyLearningRoute = MyLearningRouteImport.update({
  id: '/my-learning',
  path: '/my-learning',
  getParentRoute: () => rootRouteImport,
} as any)
const OnyeOziRoute = OnyeOziRouteImport.update({
  id: '/onye-ozi',
  path: '/onye-ozi',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesRoute = ProgrammesRouteImport.update({
  id: '/programmes',
  path: '/programmes',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const TranscriptRoute = TranscriptRouteImport.update({
  id: '/transcript',
  path: '/transcript',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentSlugRoute = AssessmentSlugRouteImport.update({
  id: '/assessment/$slug',
  path: '/assessment/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengeSlugRoute = ChallengeSlugRouteImport.update({
  id: '/challenge/$slug',
  path: '/challenge/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptsSlugRoute = ConceptsSlugRouteImport.update({
  id: '/concepts/$slug',
  path: '/concepts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CulturesSlugRoute = CulturesSlugRouteImport.update({
  id: '/cultures/$slug',
  path: '/cultures/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticSlugRoute = DiagnosticSlugRouteImport.update({
  id: '/diagnostic/$slug',
  path: '/diagnostic/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnSlugRoute = LearnSlugRouteImport.update({
  id: '/learn/$slug',
  path: '/learn/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PathsIndexRoute = PathsIndexRouteImport.update({
  id: '/paths/',
  path: '/paths/',
  getParentRoute: () => rootRouteImport,
} as any)
const PathsSlugRoute = PathsSlugRouteImport.update({
  id: '/paths/$slug',
  path: '/paths/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeSlugRoute = PracticeSlugRouteImport.update({
  id: '/practice/$slug',
  path: '/practice/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesSlugRoute = ProgrammesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProgrammesRoute,
} as any)
const RegionsSlugRoute = RegionsSlugRouteImport.update({
  id: '/regions/$slug',
  path: '/regions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchSlugRoute = ResearchSlugRouteImport.update({
  id: '/research/$slug',
  path: '/research/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesSlugRoute = SourcesSlugRouteImport.update({
  id: '/sources/$slug',
  path: '/sources/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsSlugRoute = SubjectsSlugRouteImport.update({
  id: '/subjects/$slug',
  path: '/subjects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UnitsSlugRoute = UnitsSlugRouteImport.update({
  id: '/units/$slug',
  path: '/units/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/certificates': typeof CertificatesRoute
  '/classroom': typeof ClassroomRoute
  '/compare': typeof CompareRoute
  '/explore': typeof ExploreRoute
  '/instructors': typeof InstructorsRoute
  '/map': typeof MapRoute
  '/mastery': typeof MasteryRoute
  '/my-learning': typeof MyLearningRoute
  '/onye-ozi': typeof OnyeOziRoute
  '/programmes': typeof ProgrammesRouteWithChildren
  '/resources': typeof ResourcesRoute
  '/search': typeof SearchRoute
  '/timeline': typeof TimelineRoute
  '/transcript': typeof TranscriptRoute
  '/assessment/$slug': typeof AssessmentSlugRoute
  '/challenge/$slug': typeof ChallengeSlugRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/concepts/$slug': typeof ConceptsSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/cultures/$slug': typeof CulturesSlugRoute
  '/diagnostic/$slug': typeof DiagnosticSlugRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/paths/$slug': typeof PathsSlugRoute
  '/practice/$slug': typeof PracticeSlugRoute
  '/programmes/$slug': typeof ProgrammesSlugRoute
  '/regions/$slug': typeof RegionsSlugRoute
  '/research/$slug': typeof ResearchSlugRoute
  '/sources/$slug': typeof SourcesSlugRoute
  '/subjects/$slug': typeof SubjectsSlugRoute
  '/units/$slug': typeof UnitsSlugRoute
  '/courses/': typeof CoursesIndexRoute
  '/paths/': typeof PathsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/certificates': typeof CertificatesRoute
  '/classroom': typeof ClassroomRoute
  '/compare': typeof CompareRoute
  '/explore': typeof ExploreRoute
  '/instructors': typeof InstructorsRoute
  '/map': typeof MapRoute
  '/mastery': typeof MasteryRoute
  '/my-learning': typeof MyLearningRoute
  '/onye-ozi': typeof OnyeOziRoute
  '/programmes': typeof ProgrammesRouteWithChildren
  '/resources': typeof ResourcesRoute
  '/search': typeof SearchRoute
  '/timeline': typeof TimelineRoute
  '/transcript': typeof TranscriptRoute
  '/assessment/$slug': typeof AssessmentSlugRoute
  '/challenge/$slug': typeof ChallengeSlugRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/concepts/$slug': typeof ConceptsSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/cultures/$slug': typeof CulturesSlugRoute
  '/diagnostic/$slug': typeof DiagnosticSlugRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/paths/$slug': typeof PathsSlugRoute
  '/practice/$slug': typeof PracticeSlugRoute
  '/programmes/$slug': typeof ProgrammesSlugRoute
  '/regions/$slug': typeof RegionsSlugRoute
  '/research/$slug': typeof ResearchSlugRoute
  '/sources/$slug': typeof SourcesSlugRoute
  '/subjects/$slug': typeof SubjectsSlugRoute
  '/units/$slug': typeof UnitsSlugRoute
  '/courses': typeof CoursesIndexRoute
  '/paths': typeof PathsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/certificates': typeof CertificatesRoute
  '/classroom': typeof ClassroomRoute
  '/compare': typeof CompareRoute
  '/explore': typeof ExploreRoute
  '/instructors': typeof InstructorsRoute
  '/map': typeof MapRoute
  '/mastery': typeof MasteryRoute
  '/my-learning': typeof MyLearningRoute
  '/onye-ozi': typeof OnyeOziRoute
  '/programmes': typeof ProgrammesRouteWithChildren
  '/resources': typeof ResourcesRoute
  '/search': typeof SearchRoute
  '/timeline': typeof TimelineRoute
  '/transcript': typeof TranscriptRoute
  '/assessment/$slug': typeof AssessmentSlugRoute
  '/challenge/$slug': typeof ChallengeSlugRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/concepts/$slug': typeof ConceptsSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/cultures/$slug': typeof CulturesSlugRoute
  '/diagnostic/$slug': typeof DiagnosticSlugRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/paths/$slug': typeof PathsSlugRoute
  '/practice/$slug': typeof PracticeSlugRoute
  '/programmes/$slug': typeof ProgrammesSlugRoute
  '/regions/$slug': typeof RegionsSlugRoute
  '/research/$slug': typeof ResearchSlugRoute
  '/sources/$slug': typeof SourcesSlugRoute
  '/subjects/$slug': typeof SubjectsSlugRoute
  '/units/$slug': typeof UnitsSlugRoute
  '/courses/': typeof CoursesIndexRoute
  '/paths/': typeof PathsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/certificates'
    | '/classroom'
    | '/compare'
    | '/explore'
    | '/instructors'
    | '/map'
    | '/mastery'
    | '/my-learning'
    | '/onye-ozi'
    | '/programmes'
    | '/resources'
    | '/search'
    | '/timeline'
    | '/transcript'
    | '/assessment/$slug'
    | '/challenge/$slug'
    | '/collections/$slug'
    | '/concepts/$slug'
    | '/courses/$slug'
    | '/cultures/$slug'
    | '/diagnostic/$slug'
    | '/learn/$slug'
    | '/paths/$slug'
    | '/practice/$slug'
    | '/programmes/$slug'
    | '/regions/$slug'
    | '/research/$slug'
    | '/sources/$slug'
    | '/subjects/$slug'
    | '/units/$slug'
    | '/courses/'
    | '/paths/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/certificates'
    | '/classroom'
    | '/compare'
    | '/explore'
    | '/instructors'
    | '/map'
    | '/mastery'
    | '/my-learning'
    | '/onye-ozi'
    | '/programmes'
    | '/resources'
    | '/search'
    | '/timeline'
    | '/transcript'
    | '/assessment/$slug'
    | '/challenge/$slug'
    | '/collections/$slug'
    | '/concepts/$slug'
    | '/courses/$slug'
    | '/cultures/$slug'
    | '/diagnostic/$slug'
    | '/learn/$slug'
    | '/paths/$slug'
    | '/practice/$slug'
    | '/programmes/$slug'
    | '/regions/$slug'
    | '/research/$slug'
    | '/sources/$slug'
    | '/subjects/$slug'
    | '/units/$slug'
    | '/courses'
    | '/paths'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/certificates'
    | '/classroom'
    | '/compare'
    | '/explore'
    | '/instructors'
    | '/map'
    | '/mastery'
    | '/my-learning'
    | '/onye-ozi'
    | '/programmes'
    | '/resources'
    | '/search'
    | '/timeline'
    | '/transcript'
    | '/assessment/$slug'
    | '/challenge/$slug'
    | '/collections/$slug'
    | '/concepts/$slug'
    | '/courses/$slug'
    | '/cultures/$slug'
    | '/diagnostic/$slug'
    | '/learn/$slug'
    | '/paths/$slug'
    | '/practice/$slug'
    | '/programmes/$slug'
    | '/regions/$slug'
    | '/research/$slug'
    | '/sources/$slug'
    | '/subjects/$slug'
    | '/units/$slug'
    | '/courses/'
    | '/paths/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  CertificatesRoute: typeof CertificatesRoute
  ClassroomRoute: typeof ClassroomRoute
  CompareRoute: typeof CompareRoute
  ExploreRoute: typeof ExploreRoute
  InstructorsRoute: typeof InstructorsRoute
  MapRoute: typeof MapRoute
  MasteryRoute: typeof MasteryRoute
  MyLearningRoute: typeof MyLearningRoute
  OnyeOziRoute: typeof OnyeOziRoute
  ProgrammesRoute: typeof ProgrammesRouteWithChildren
  ResourcesRoute: typeof ResourcesRoute
  SearchRoute: typeof SearchRoute
  TimelineRoute: typeof TimelineRoute
  TranscriptRoute: typeof TranscriptRoute
  AssessmentSlugRoute: typeof AssessmentSlugRoute
  ChallengeSlugRoute: typeof ChallengeSlugRoute
  CollectionsSlugRoute: typeof CollectionsSlugRoute
  ConceptsSlugRoute: typeof ConceptsSlugRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
  CulturesSlugRoute: typeof CulturesSlugRoute
  DiagnosticSlugRoute: typeof DiagnosticSlugRoute
  LearnSlugRoute: typeof LearnSlugRoute
  PathsSlugRoute: typeof PathsSlugRoute
  PracticeSlugRoute: typeof PracticeSlugRoute
  RegionsSlugRoute: typeof RegionsSlugRoute
  ResearchSlugRoute: typeof ResearchSlugRoute
  SourcesSlugRoute: typeof SourcesSlugRoute
  SubjectsSlugRoute: typeof SubjectsSlugRoute
  UnitsSlugRoute: typeof UnitsSlugRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  PathsIndexRoute: typeof PathsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates': {
      id: '/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof CertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classroom': {
      id: '/classroom'
      path: '/classroom'
      fullPath: '/classroom'
      preLoaderRoute: typeof ClassroomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructors': {
      id: '/instructors'
      path: '/instructors'
      fullPath: '/instructors'
      preLoaderRoute: typeof InstructorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mastery': {
      id: '/mastery'
      path: '/mastery'
      fullPath: '/mastery'
      preLoaderRoute: typeof MasteryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-learning': {
      id: '/my-learning'
      path: '/my-learning'
      fullPath: '/my-learning'
      preLoaderRoute: typeof MyLearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onye-ozi': {
      id: '/onye-ozi'
      path: '/onye-ozi'
      fullPath: '/onye-ozi'
      preLoaderRoute: typeof OnyeOziRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes': {
      id: '/programmes'
      path: '/programmes'
      fullPath: '/programmes'
      preLoaderRoute: typeof ProgrammesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transcript': {
      id: '/transcript'
      path: '/transcript'
      fullPath: '/transcript'
      preLoaderRoute: typeof TranscriptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/$slug': {
      id: '/assessment/$slug'
      path: '/assessment/$slug'
      fullPath: '/assessment/$slug'
      preLoaderRoute: typeof AssessmentSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenge/$slug': {
      id: '/challenge/$slug'
      path: '/challenge/$slug'
      fullPath: '/challenge/$slug'
      preLoaderRoute: typeof ChallengeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concepts/$slug': {
      id: '/concepts/$slug'
      path: '/concepts/$slug'
      fullPath: '/concepts/$slug'
      preLoaderRoute: typeof ConceptsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cultures/$slug': {
      id: '/cultures/$slug'
      path: '/cultures/$slug'
      fullPath: '/cultures/$slug'
      preLoaderRoute: typeof CulturesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostic/$slug': {
      id: '/diagnostic/$slug'
      path: '/diagnostic/$slug'
      fullPath: '/diagnostic/$slug'
      preLoaderRoute: typeof DiagnosticSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$slug': {
      id: '/learn/$slug'
      path: '/learn/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof LearnSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paths/': {
      id: '/paths/'
      path: '/paths'
      fullPath: '/paths/'
      preLoaderRoute: typeof PathsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paths/$slug': {
      id: '/paths/$slug'
      path: '/paths/$slug'
      fullPath: '/paths/$slug'
      preLoaderRoute: typeof PathsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/$slug': {
      id: '/practice/$slug'
      path: '/practice/$slug'
      fullPath: '/practice/$slug'
      preLoaderRoute: typeof PracticeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/$slug': {
      id: '/programmes/$slug'
      path: '/$slug'
      fullPath: '/programmes/$slug'
      preLoaderRoute: typeof ProgrammesSlugRouteImport
      parentRoute: typeof ProgrammesRoute
    }
    '/regions/$slug': {
      id: '/regions/$slug'
      path: '/regions/$slug'
      fullPath: '/regions/$slug'
      preLoaderRoute: typeof RegionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/$slug': {
      id: '/research/$slug'
      path: '/research/$slug'
      fullPath: '/research/$slug'
      preLoaderRoute: typeof ResearchSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/$slug': {
      id: '/sources/$slug'
      path: '/sources/$slug'
      fullPath: '/sources/$slug'
      preLoaderRoute: typeof SourcesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/$slug': {
      id: '/subjects/$slug'
      path: '/subjects/$slug'
      fullPath: '/subjects/$slug'
      preLoaderRoute: typeof SubjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/units/$slug': {
      id: '/units/$slug'
      path: '/units/$slug'
      fullPath: '/units/$slug'
      preLoaderRoute: typeof UnitsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProgrammesRouteChildren {
  ProgrammesSlugRoute: typeof ProgrammesSlugRoute
}

const ProgrammesRouteChildren: ProgrammesRouteChildren = {
  ProgrammesSlugRoute: ProgrammesSlugRoute,
}

const ProgrammesRouteWithChildren = ProgrammesRoute._addFileChildren(
  ProgrammesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  CertificatesRoute: CertificatesRoute,
  ClassroomRoute: ClassroomRoute,
  CompareRoute: CompareRoute,
  ExploreRoute: ExploreRoute,
  InstructorsRoute: InstructorsRoute,
  MapRoute: MapRoute,
  MasteryRoute: MasteryRoute,
  MyLearningRoute: MyLearningRoute,
  OnyeOziRoute: OnyeOziRoute,
  ProgrammesRoute: ProgrammesRouteWithChildren,
  ResourcesRoute: ResourcesRoute,
  SearchRoute: SearchRoute,
  TimelineRoute: TimelineRoute,
  TranscriptRoute: TranscriptRoute,
  AssessmentSlugRoute: AssessmentSlugRoute,
  ChallengeSlugRoute: ChallengeSlugRoute,
  CollectionsSlugRoute: CollectionsSlugRoute,
  ConceptsSlugRoute: ConceptsSlugRoute,
  CoursesSlugRoute: CoursesSlugRoute,
  CulturesSlugRoute: CulturesSlugRoute,
  DiagnosticSlugRoute: DiagnosticSlugRoute,
  LearnSlugRoute: LearnSlugRoute,
  PathsSlugRoute: PathsSlugRoute,
  PracticeSlugRoute: PracticeSlugRoute,
  RegionsSlugRoute: RegionsSlugRoute,
  ResearchSlugRoute: ResearchSlugRoute,
  SourcesSlugRoute: SourcesSlugRoute,
  SubjectsSlugRoute: SubjectsSlugRoute,
  UnitsSlugRoute: UnitsSlugRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  PathsIndexRoute: PathsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
